# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BIC_logit_NDH <- function(A, object) {
    .Call('_JANE_BIC_logit_NDH', PACKAGE = 'JANE', A, object)
}

BIC_logit_RS <- function(A, object) {
    .Call('_JANE_BIC_logit_RS', PACKAGE = 'JANE', A, object)
}

BIC_logit_RSR <- function(A, object) {
    .Call('_JANE_BIC_logit_RSR', PACKAGE = 'JANE', A, object)
}

BIC_ICL_MBC <- function(object) {
    .Call('_JANE_BIC_ICL_MBC', PACKAGE = 'JANE', object)
}

log_like_C <- function(par, X, y) {
    .Call('_JANE_log_like_C', PACKAGE = 'JANE', par, X, y)
}

gradient_C <- function(par, X, y) {
    .Call('_JANE_gradient_C', PACKAGE = 'JANE', par, X, y)
}

compute_dist <- function(U, distances, model, X, indices, downsampling) {
    invisible(.Call('_JANE_compute_dist', PACKAGE = 'JANE', U, distances, model, X, indices, downsampling))
}

log_Q <- function(A, U, mus, omegas, prob_matrix, beta, p, a, b, c, G, nu, e, f, X, n_control, model) {
    .Call('_JANE_log_Q', PACKAGE = 'JANE', A, U, mus, omegas, prob_matrix, beta, p, a, b, c, G, nu, e, f, X, n_control, model)
}

log_Q_RE <- function(A, U, mus, omegas, prob_matrix, beta, p, a, b, c, G, nu, e, f, X, model, n_control) {
    .Call('_JANE_log_Q_RE', PACKAGE = 'JANE', A, U, mus, omegas, prob_matrix, beta, p, a, b, c, G, nu, e, f, X, model, n_control)
}

draw_A_NDH_c <- function(U, beta0) {
    .Call('_JANE_draw_A_NDH_c', PACKAGE = 'JANE', U, beta0)
}

draw_A_RS_c <- function(U, beta0, s) {
    .Call('_JANE_draw_A_RS_c', PACKAGE = 'JANE', U, beta0, s)
}

draw_A_RSR_c <- function(U, beta0, s, r) {
    .Call('_JANE_draw_A_RSR_c', PACKAGE = 'JANE', U, beta0, s, r)
}

update_U <- function(U, A, mus, omegas, prob_matrix, beta, X, n_control, model) {
    invisible(.Call('_JANE_update_U', PACKAGE = 'JANE', U, A, mus, omegas, prob_matrix, beta, X, n_control, model))
}

update_U_CC <- function(U, n_control, A, mus, omegas, prob_matrix, beta, X, model) {
    invisible(.Call('_JANE_update_U_CC', PACKAGE = 'JANE', U, n_control, A, mus, omegas, prob_matrix, beta, X, model))
}

update_U_RE <- function(U, A, mus, omegas, prob_matrix, beta, X, model, n_control) {
    invisible(.Call('_JANE_update_U_RE', PACKAGE = 'JANE', U, A, mus, omegas, prob_matrix, beta, X, model, n_control))
}

update_U_RE_CC <- function(U, n_control, A, mus, omegas, prob_matrix, beta, X, model) {
    invisible(.Call('_JANE_update_U_RE_CC', PACKAGE = 'JANE', U, n_control, A, mus, omegas, prob_matrix, beta, X, model))
}

update_beta <- function(beta, A, U, f, e, X, n_control, model) {
    invisible(.Call('_JANE_update_beta', PACKAGE = 'JANE', beta, A, U, f, e, X, n_control, model))
}

update_beta_CC <- function(beta, A, n_control, U, f, e, X, model) {
    invisible(.Call('_JANE_update_beta_CC', PACKAGE = 'JANE', beta, A, n_control, U, f, e, X, model))
}

update_beta_RE <- function(beta, A, U, f, e, X, model, n_control) {
    invisible(.Call('_JANE_update_beta_RE', PACKAGE = 'JANE', beta, A, U, f, e, X, model, n_control))
}

update_beta_RE_CC <- function(beta, A, n_control, U, f, e, X, model) {
    invisible(.Call('_JANE_update_beta_RE_CC', PACKAGE = 'JANE', beta, A, n_control, U, f, e, X, model))
}

update_mus_omegas <- function(prob_matrix, U, b, a, c, G, mus, omegas) {
    invisible(.Call('_JANE_update_mus_omegas', PACKAGE = 'JANE', prob_matrix, U, b, a, c, G, mus, omegas))
}

update_p <- function(prob_matrix, p, nu) {
    invisible(.Call('_JANE_update_p', PACKAGE = 'JANE', prob_matrix, p, nu))
}

update_prob_matrix_DA <- function(prob_matrix, mus, omegas, p, U, temp_beta) {
    invisible(.Call('_JANE_update_prob_matrix_DA', PACKAGE = 'JANE', prob_matrix, mus, omegas, p, U, temp_beta))
}

